import '../app/globals.css'
import type { AppProps } from 'next/app'
import type { Metadata } from 'next'
import Layout from "../components/Layout"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Layout>
      <Component {...pageProps} />
    </Layout>
  )
}

export default MyApp
